---
name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - uses: codespell-project/actions-codespell@master
    - uses: chartboost/ruff-action@v1
    - name: Run yamllint
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: "./"
        config_file: "./.yaml-lint.yaml"
        strict: true
